### ISSUE TITLE
Suggestion to prefix input names with their types

### ISSUE THREAD

**Issue by believer-ufa** [voorhoede/riotjs-style-guide#35]
Thanks for this nice style guide)

I suggest to add this rule of naming inputs: _always prefix input names with their types_.

**Why?**

Riot.js attaches all input fields to our tag, and they are easy to mix with all the other variables. Therefore, if we make the prefixes for all input fields (and selects,, indicating their type, it will facilitate our analysis of the tag.

**How?**

``` html
<!-- recommended -->
<component1>
  <input name="input_email" value='user@gmail.com' />
  <textarea name="textarea_comment"></textarea>
  <script>
    var tag = this
    console.log(tag.input_email.value)
    console.log(tag.textarea_comment.value)
  </script>
</component1>

<!-- avoid -->
<component1>
  <input name="email" value='user@gmail.com' />
  <textarea name="comment"></textarea>

  <script>
    var tag = this

    // its inputs or just variables? Unknown until you learn all component
    console.log(tag.email.value)
    console.log(tag.comment.value)
  </script>
</component1>
```

**Comment by jbmoelker** [comment]
I understand your point. However I'd consider Riot's behaviour to bind form inputs to the tag instance by their name a case of Riot magic. While it may come in handy, I'd wish Riot would take it out. 
By default when a form on a web page is submitted, it takes the values of the form inputs by their names as data. The endpoint to which the form is posted can then use that data: 

> When a form is submitted for processing, some controls have their name paired with their current value and these pairs are submitted with the form. Those controls for which name/value pairs are submitted are called successful controls.
> -- [W3C on forms](https://www.w3.org/TR/html401/interact/forms.html#form-controls)

Since Riot tags are only responsible for the UI, they shouldn't dictate the data structure send to an endpoint. Otherwise back-ends may have to change because we want Riot to do something in a certain way. And we always try to avoid such a vendor lock.

Instead, I would attempt to just stay closer to the web standards. Inputs have always been available by name on the `form` they are in. You could use it like this:

``` html
<component1>
  <form onsubmit="{ onSubmit }">
    <input name="email" value='user@gmail.com' />
    <textarea name="comment"></textarea>
  </form>

  <script>
    var tag = this;
    tag.onSubmit = onSubmit;

    function onSubmit (event) {
        var form = tag.root.querySelector('form'); // or get from event
        console.log(form.email.value);
        console.log(form.comment.value);
    }
  </script>
</component1>
```

You are still free to use your input naming strategy, because it could save you from conflicts with other tag instance properties, but I wouldn't force it.

**Comment by believer-ufa** [comment]
Thanks) Yes, its a problem - data sends to server with this prefixes. I use this approach in forms that dont send data to backend.

**Comment by jbmoelker** [comment]
React handles this better, by namespacing all element references in [`.refs`](https://facebook.github.io/react/docs/more-about-refs.html#the-ref-string-attribute). In my opinion the way Riot handles this is a design flaw. It fits well within Riot's "write less" approach, but it can definitely cause confusion. 

Since we haven't come to a _rule_ for this guide which can always be applied, I'm closing this issue. Feel free to re-open when there are new suggestions.

**Comment by jbmoelker** [comment]
[Riot v3.0 supports `.refs`](http://riotjs.com/guide/#named-elements).

**Comment by believer-ufa** [comment]
Yeah, this is really nice improvement, thanks to riot.js authors :) Its completely solve this problem.
