### ISSUE TITLE
DRY code instead of redeclaring "magic es6 methods"

### ISSUE THREAD

**Issue by MartinMuzatko** [voorhoede/riotjs-style-guide#51]
I agree that the so called magic es6 methods  `add() {}` was confusing first, but it is riot-specific and usually 

But I'd avoid writing up the additional `tag.add = add` and rather use the original syntax or write `this.add = function() {}.bind(this)`instead of this:

``` js
tag.add = add;

function add() {
    if (tag.text) {
        tag.todos.push({ title: tag.text });
        tag.text = tag.input.value = '';
    }
}
```

Discussion?

**Comment by jbmoelker** [comment]
@MartinMuzatko `add() {}` is non-standard. Both `tag.add = add;` and `this.add = function() {}.bind(this)` are both at least valid JavaScript.

I think the rest comes down to preference. We have a preference to "[put tag properties and methods on top](https://github.com/voorhoede/riotjs-style-guide#put-tag-properties-and-methods-on-top)", which is in turn based on [Angular Style Guide > "Bindable members on top"](https://github.com/johnpapa/angular-styleguide/blob/master/a1/README.md#bindable-members-up-top). In short it ensures you get a "table of contents of a tag's properties and methods" and that's why it works well for us.

**Comment by MartinMuzatko** [comment]
Thanks for explaining. I have to admit it is confusing when mixing event handlers and "private" methods
